# NOTE: This is based off of the example template here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["sfbrigade/7"],
assignees:
  - juliagulia
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? (feel free to also attach a screenshot or video)
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What should have happened instead?
      description: And what behavior did you expect to happen instead?
      placeholder: Tell us what you expect!
      value: "This should have happened instead!"
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Did you see this bug on the production or development version of the website? (If you're not sure, you can leave this as default)
      options:
        - supportsfschools.org (Production)
        - support-sfusd.vercel.app (Development)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Microsoft Edge
        - Firefox
  - type: dropdown
    id: platforms
    attributes:
      label: Which platform(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - iOS
        - Android
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
